Munhak-Zip/Munhak.Zip_Front

src/page/user/Mihkim.js
=> add: github test

src/page/movie/Movie.js
=> add: Movie.js 추가 및 github test 

src/App.js, src/page/user/Main.js
=> [add/#1] 메인 추가

src/resources/css/Movie/MovieDetail.css, src/views/movie/MovieDetail.js
별점 예측이 아니라 영화에 대한 긍정,부정 내용 요약해주기로 해서 ui변경
=> [fix/#1] 영화 상세 이미지 변경

src/App.js, src/page/user/Main.js, src/resources/css/Movie/MovieList.css, src/views/movie/MovieList.js
MovieList.js 구현
좋아하는 영화, 추천 영화, 최신 영화 등 요소 변경은 이후 controller로 요청 처리 하면서 수정 해야함
지금은 정적으로 설정
=> [add/#23]MovieList.js 구현

src/App.js, src/page/user/Main.js, src/resources/css/Movie/MovieList.css, src/resources/css/Wish/Wish.css, src/views/movie/MovieList.js, src/views/wish/Wish.js
보관함 메인화면 구현 완료 
화살표 누르면 페이지 이동
=> [add/#25]Wish.js 완료

src/App.js, src/page/user/Main.js, src/resources/css/Movie/MovieList.css, src/resources/css/Movie/Reserve.css, src/resources/css/Wish/Wish.css, src/views/movie/MovieList.js, src/views/movie/Reserve.js, src/views/wish/Wish.js
=> [add/#29]예매 페이지 추가

package-lock.json, package.json, src/App.js, src/setProxy.js
=> [fix/#37]Main화면 처음에 뜨도록 수정

src/App.js, src/views/Main.js
백엔드 연동 (MovieRecommendController)
Main.js에 추천 영화 출력, 백엔드 연동 O
=> [add/#37]추천 영화 출력

src/App.js, src/views/Main.js, src/views/movie/MovieDetail.js
추천 영화 이미지 띄우기, 이미지 클릭 시 MovieDetail.js로 이동
추천 영화 이미지 띄우기, 이미지 클릭 시 MovieDetail.js로 이동
=> [fix#45] MovieDetail.js로 이동

src/page/user/Main.js, src/resources/css/Movie/MovieDetail.css, src/views/Main.js, src/views/movie/MovieDetail.js
영화 디테일 화면 연결~ 
css파일도 조금 수정했음다
백에 영화 id넣어줌
=> [feat/#45] 영화 디테일 연결

src/App.js, src/views/movie/MovieDetail.js, src/views/movie/Reserve.js
MovieDetail.js -> Reserve.js 연결
예매하기 클릭 시 Reserve.js
=> [add#45]Reserve.js 연결

src/views/movie/Reserve.js
=> [fea/#45] 영화 예매 화면

package-lock.json, package.json, src/views/Main.js
=> [feat/#45] 추천영화 로딩 화면 구현

src/App.js, src/axiosConfig.js, src/components/common/Sidebar.js, src/components/common/header.js, src/views/mypage/Mypage.js, src/views/user/Login.js, src/views/user/Logout.js
=> [fix/#52]로그인 여부에 따른 사이드 바 화면 조절

src/App.js, src/views/movie/Reserve.js, src/views/mypage/Mypage.js
예매 후 마이페이지에서 확인 (아직은 좌석만 확인 가능)
예매 후 마이페이지에서 확인
=> [feat#45]예매 -> 마이페이지

src/components/common/header.js, src/index.js, src/views/Main.js, src/views/mypage/Mypage.js
로컬스토리지에 사용자 고유 아이디 저장했습니다. 빼서 사용하면 될듯요!
백엔드 코드
프론트 연결 코드
=>  [add/#55] 사용자 고유 아이디 가져오기

src/resources/css/Mypage/Mypage.css, src/views/movie/Reserve.js, src/views/mypage/Mypage.js
=> [feat/#45] 예매내역 마이페이지 출력

src/views/Main.js, src/views/mypage/Mypage.js
=> [feat/#58]최신 영화 5개 조회

src/App.js, src/views/movie/Reserve.js, src/views/mypage/Mypage.js
예매, 마이페이지 아이디 세션 변경
이 작업은 뭐에 대한거고 어쩌구저쩌구
=> [feat/#45]아이디 세션 변경

src/views/movie/MovieDetail.js
=> [feat/#61]리뷰 작성 추가

src/views/movie/MovieDetail.js
=> [feat/#64] 평론가 리뷰 제공

src/resources/css/Main/Main.css, src/views/Main.js, src/views/movie/MovieDetail.js
=> [feat/#76] 메인화면 보관함 영화 출력

src/views/mypage/Mypage.js
마이페이지 회원 정보 출력
이 작업은 뭐에 대한거고 어쩌구저쩌구
=> [feat] 마이페이지 회원 정보 출력 #76

src/resources/css/Wish/ReviewDetail.css, src/resources/css/Wish/WishReviewList.css, src/views/wish/MyReviewList.js, src/views/wish/Wish.js, src/views/wish/WishReviewList.js
css 충돌있어서 이름 다 바꿨습니다
이제 충돌 안나요
=> [fix/#72] myreviewdetail css 수정

src/views/movie/MovieDetail.js
=> [feat/#61]리뷰 작성 오류 수정
